---
- name: Install console utilities
  aur:
    name:
      - docker
      - docker-compose
      - htop
      - lshw
      - man-db
      - mc
      - nmap
      - ntfs-3g
      - powertop
      - python2
      - rsync
      - samba
      - wget
      - xz
  become: yes
  become_user: "{{ aur_user }}"
