---
- name: Create /root/scripts directory
  ansible.builtin.file:
    path: /root/scripts
    state: directory
    mode: "0700"
    owner: root
    group: root
  become: true
  tags:
    - copy


- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group | default(item.owner) }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"
  vars:
    files:
      - src: root_scripts/
        dest: /root/scripts/
        mode: "0700"
        owner: root
      - src: systemd/usb_mouse_fix.service
        dest: /etc/systemd/system/usb_mouse_fix.service
        mode: "0664"
        owner: root
  notify:
    - Reload_systemd
  become: true
  tags:
    - copy


- name: Enable service
  ansible.builtin.systemd:
    name: usb_mouse_fix
    enabled: true
    masked: false
  become: true
  tags:
    - systemd
