---
- name: Create /root/scripts directory
  file:
    path: /root/scripts
    state: directory
    mode: "0700"
    owner: root
    group: root
  become: yes
  tags:
    - copy


- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group|default(item.owner) }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"
  vars:
    files:
      - src: root_scripts/
        dest: /root/scripts/
        mode: "0700"
        owner: root
      - src: systemd/usb_mouse_fix.service
        dest: /etc/systemd/system/usb_mouse_fix.service
        mode: "0664"
        owner: root
  notify:
    - reload systemd
  become: yes
  tags:
    - copy


- name: Enable service
  systemd:
    name: usb_mouse_fix
    enabled: yes
    masked: no
  become: yes
  tags:
    - systemd
