---
- name: Install packages
  ansible.builtin.apt:
    name: '{{ install_packages_ubuntu.apt }}'
    state: present
    update_cache: true
  become: true
  when: ubuntu.apt is defined
  tags:
    - wallpaper
