---
#- name: Run the equivalent of "pacman -Syu" as a separate step
#  pacman:
#    update_cache: true
#    upgrade: true
#  become: true
#  tags:
#    - update
#    - upgrade


- name: Install packages
  kewlfft.aur.aur:
    name: '{{ Arch.aur }}'
  become: true
  become_user: "{{ aur_user }}"
  when: Arch.aur is defined
  tags:
    - wallpaper
