---
- name: Run the equivalent of "pacman -Syu" as a separate step
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes
  tags:
    - update
    - upgrade


- name: Install
  pacman:
    name:
      - ansible
      - bind-tools
      - bluez
      - chromium
      - cinnamon
      - cronie
      - cups
      - curl
      - deadbeef
      - docker
      - docker-compose
      - faenza-icon-theme
      - file-roller
      - filezilla
      - firefox
      - geany
      - git
      - gpicview-gtk3
      - guake
      - inetutils
      - jre-openjdk
      - libreoffice-fresh
      - lightdm
      - lightdm-gtk-greeter
      - lm_sensors
      - man-db
      - mc
      - mpv
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
      - networkmanager-pptp
      - nmap
      - ntfs-3g
      - nextcloud-client
      - p7zip
      - powertop
      - python2
      - rdesktop
      - remmina
      - rsync
      - samba
      - smplayer
      - smplayer-themes
      - tigervnc
      - vim
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-host-modules-arch
      - wget
      - wqy-bitmapfont
      - wqy-zenhei
      - xz
    state: present
  tags:
    - install