---
- include_tasks:
    file: do_install_cinnamon.yml
  when: arch in ansible_distribution
  tags:
    - install
    - cinnamon


- name: Create scripts directory
  file:
    path: $HOME/scripts
    state: directory
    mode: 0700
  tags:
    - configure
    - cinnamon
    - scripts


- name: Copy user scripts
  copy:
    src: user_scripts/
    dest: $HOME/scripts/
    mode: 0700
  tags:
    - configure
    - cinnamon
    - scripts


- name: Configure cinnamon
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ cinnamon_config }}"
  tags:
    - configure
    - cinnamon
    - dconf


- name: Create cinnamon config directory
  file:
    path: $HOME/.cinnamon/configs
    state: directory
    mode: 0755
  tags:
    - configure
    - cinnamon


- name: Copy cinnamon configs
  copy:
    src: cinnamon_configs/
    dest: $HOME/.cinnamon/configs/
  tags:
    - configure
    - cinnamon
