---
- name: Install cinnamon
  aur:
    name:
      - cinnamon
      - nemo
      - nemo-fileroller
      - cinnamon-sound-effects
      - cinnamon-theme-numix-git
      - faenza-icon-theme
      - adwaita-icon-theme
      - capitaine-cursors
      - xclip
    skip_installed: yes
  become: yes
  become_user: "{{ aur_user }}"
  tags:
    - install
    - cinnamon


- name: Create scripts directory
  file:
    path: $HOME/scripts
    state: directory
    mode: 0700
  tags:
    - configure
    - cinnamon
    - scripts


- name: Copy user scripts
  copy:
    src: user_scripts/
    dest: $HOME/scripts/
    mode: 0700
  tags:
    - configure
    - cinnamon
    - scripts


- name: Configure cinnamon
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ cinnamon_config }}"
  tags:
    - configure
    - cinnamon


- name: Create cinnamon config directory
  file:
    path: $HOME/.cinnamon/configs
    state: directory
    mode: 0755
  tags:
    - configure
    - cinnamon


- name: Copy cinnamon configs
  copy:
    src: cinnamon_configs/
    dest: $HOME/.connamon/configs
  tags:
    - configure
    - cinnamon
