---
- name: Install Arch Linux packages
  ansible.builtin.package:
    name:
      - hyprland-per-window-layout
      - swaync
    state: present

- name: Remove Mako
  ansible.builtin.package:
    name: mako
    state: absent
