---
- name: Install Arch Linux packages
  ansible.builtin.package:
    name:
      - grim
      - hyprland-per-window-layout
      - jq
      - slurp
      - swaync
      - wl-clipboard
    state: present
  become: true

- name: Remove Mako
  ansible.builtin.package:
    name: mako
    state: absent
  become: true
