---
- name: Distribution-specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['distribution'] | lower }}.yml"

- name: Install packages
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - blueman
      - brightnessctl
      - foot
      - fuzzel
      - hypridle
      - hyprland
      - hyprlock
      - hyprpaper
      - hyprpwcenter
      - playerctl
      - waybar

- name: Add current user to input group required by Waybar
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: input
    append: true

- name: Disable Hypridle user service
  ansible.builtin.systemd_service:
    name: hypridle.service
    enabled: false
    scope: user

- name: Create config dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - ~/.config/foot
    - ~/.config/fuzzel
    - ~/.config/hypr
    - ~/.config/mako
    - ~/.config/waybar

- name: Copy hypr config
  ansible.builtin.copy:
    src: config/hypr
    dest: ~/.config/
    directory_mode: "0700"
    mode: "0600"
  notify: restart_hypridle

- name: Copy waybar config
  ansible.builtin.copy:
    src: config/waybar
    dest: ~/.config/
    directory_mode: "0700"
    mode: "0600"
  notify: reload_waybar_config

- name: Copy foot config
  ansible.builtin.copy:
    src: config/foot
    dest: ~/.config/
    directory_mode: "0700"
    mode: "0600"

- name: Copy fuzzel config
  ansible.builtin.copy:
    src: config/fuzzel
    dest: ~/.config/
    directory_mode: "0700"
    mode: "0600"

- name: Copy mako config
  ansible.builtin.copy:
    src: config/mako
    dest: ~/.config/
    directory_mode: "0700"
    mode: "0600"
  notify: reload_mako_config

- name: Copy executables
  ansible.builtin.copy:
    src: local/bin
    dest: ~/.local/
    directory_mode: "0700"
    mode: "0700"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
