---
- name: Install deb822 repository support
  ansible.builtin.apt:
    name: python3-debian
    state: present
  become: true

- name: Remove legacy hyprland PPA repository
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/ppa_cppiber_hyprland_{{ ansible_facts['distribution_release'] }}.list"
    state: absent
  notify: Update hyprland apt package cache
  become: true

- name: Add hyprland PPA repository
  ansible.builtin.deb822_repository:
    name: cppiber-hyprland
    types:
      - deb
    uris:
      - https://ppa.launchpadcontent.net/cppiber/hyprland/ubuntu
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
    components:
      - main
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA54D23B62FF3FCC76EFF71E8FDBAAA1CF0CCF48E"
    state: present
  notify: update_apt_package_cache
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install Ubuntu packages
  ansible.builtin.apt:
    name:
      - cargo-1.91
      - foot-themes
      - mako-notifier
  become: true

- name: Install hyprland-per-window-layout using cargo
  community.general.cargo:
    name: hyprland-per-window-layout
    locked: true
    path: ~/.local
    executable: /usr/bin/cargo-1.91

- name: Enable Wayland for GDM3
  community.general.ini_file:
    path: /etc/gdm3/custom.conf
    section: daemon
    option: WaylandEnable
    value: "true"
  notify: gdm_restart
  become: true

- name: Download Nerd Fonts install script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/install.sh"
    dest: "/tmp/install_nerd_font.sh"
    mode: '0755'

- name: Execute the install script for JetBrainsMono
  ansible.builtin.command:
    cmd: "/tmp/install_nerd_font.sh install JetBrainsMono"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.local/share/fonts/NerdFonts"
