---
- name: Enable Spain mirror in /etc/pacman.d/mirrorlist
  ansible.builtin.replace:
    path: /etc/pacman.d/mirrorlist
    regexp: '^#Server = http:\/\/mirror.librelabucm.org\/archlinux\/\$repo\/os\/\$arch'
    replace: Server = http://mirror.librelabucm.org/archlinux/$repo/os/$arch
  become: true
  notify: update_pacman_cache
  tags:
    - configure_pacman
    - pacman
    - config


#- name: pacman.conf
#  ansible.builtin.lineinfile:
#    path: /etc/pacman.conf
#    regexp: "{{ item.regexp }}"
#    line: "{{ item.line }}"
#  with_items: lines
#  vars:
#    lines:
#      - regexp: '^#CleanMethod = KeepInstalled$'
#        line: 'CleanMethod = KeepInstalled & KeepCurrent'
#      - regexp: '^#UseDelta    = 0\.7$'
#        line: 'UseDelta    = 0.7'
#      - regexp: '^#Color$'
#        line: 'Color'
#      - regexp: '^#TotalDownload$'
#        line: 'TotalDownload'
#      - regexp: '^#\[multilib\]$'
#        line: '[multilib]'
#      - regexp:


- name: pacman.conf
  ansible.builtin.copy:
    src: files/etc/pacman.conf
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: update_pacman_cache
  tags:
    - configure_pacman
    - pacman
    - config


- name: Flush handlers now
  ansible.builtin.meta: flush_handlers
  tags:
    - configure_pacman
    - pacman
    - config
