---
guake_config:
  - key: /apps/guake/general/start-at-login
    value: 'true'
  - key: /apps/guake/general/use-popup
    value: 'false'
  - key: /apps/guake/general/use-trayicon
    value: 'false'
  - key: /apps/guake/general/gtk-theme-name
    value: "'Adwaita-dark'"
  - key: /apps/guake/general/gtk-prefer-dark-theme
    value: 'true'
  - key: /apps/guake/general/infinite-history
    value: 'true'
  - key: /apps/guake/general/quick-open-command-line
    value: "'geany %(file_path)s'"
  - key: /apps/guake/general/use-default-font
    value: 'false'
  - key: /apps/guake/general/window-halignment
    value: 2
  - key: /apps/guake/general/window-height
    value: 81
  - key: /apps/guake/general/window-width
    value: 62
  - key: /apps/guake/general/window-losefocus
    value: 'true'
  - key: /apps/guake/keybindings/local/next-tab
    value: "'<Shift>Right'"
  - key: /apps/guake/keybindings/local/previous-tab
    value: "'<Shift>Left'"
  - key: /apps/guake/style/font/palette-name
    value: "'Solarized Darcula'"
  - key: /apps/guake/style/font/style
    value: "'Hack 10'"
  - key: /apps/guake/style/background/transparency
    value: 97
