---
- name: Create scripts directory
  file:
    path: $HOME/scripts
    state: directory
    mode: 0700
  tags:
    - wallpaper


- name: Clone the python script repo
  git:
    repo: 'https://github.com/nsv777/random_wallpaper_url.git'
    dest: $HOME/scripts/random_wallpaper_url
  tags:
    - wallpaper


- include_role:
    name: install_packages
    vars_from: wallpaper
  tags:
    - wallpaper


- include_tasks:
    file: "do_add_cron_job_{{ ansible_distribution }}.yml"
  tags:
    - wallpaper


- name: Enable and start cronie daemon
  service:
    name: cronie
    state: started
    enabled: yes
  become: yes
  when: ansible_distribution == "Arch"
  tags:
    - wallpaper
