---
- name: Install vim on Arch
  ansible.builtin.include_tasks:
    file: do_install_vim.yml
  when: arch in ansible_distribution
  tags:
    - install_vim
    - vim


- name: Copy vim config
  ansible.builtin.copy:
    src: vim_config/vimrc.local
    dest: /etc/
    mode: "0644"
  become: true
  tags:
    - configure_vim
    - vim


- name: Update vim config
  ansible.builtin.lineinfile:
    path: /etc/vimrc
    regexp: '^source.*\/vimrc\.local$'
    line: 'source /etc/vimrc.local'
  become: true
  tags:
    - configure_vim
    - vim
