---
- include_tasks:
    file: do_install_vim.yml
  when: arch in ansible_distribution
  tags:
    - install_vim
    - vim


- name: Copy vim config
  copy:
    src: vim_config/vimrc.local
    dest: /etc/
  become: yes
  tags:
    - configure_vim
    - vim


- name: Update vim config
  lineinfile:
    path: /etc/vimrc
    regexp: '^source.*\/vimrc\.local$'
    line:  'source /etc/vimrc.local'
  become: yes
  tags:
    - configure_vim
    - vim
