---
- name: Install vim on Arch
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution | lower }}_install_vim.yml"

- name: Copy vim config
  ansible.builtin.copy:
    src: vim_config/vimrc.local
    dest: /etc/
    mode: "0644"
  become: true

- name: Update vim config
  ansible.builtin.lineinfile:
    path: /etc/vimrc
    regexp: '^source.*\/vimrc\.local$'
    line: 'source /etc/vimrc.local'
  become: true
