---
- name: Install packages
  aur:
    name:
      - twitch-curses
      - mpv
    skip_installed: yes
  become: yes
  become_user: "{{ aur_user }}"
  tags:
    - install_twitch_curses
    - twitch_curses
