---
- include_tasks:
    file: do_install_twitch-curses.yml
  when: arch in ansible_distribution
  tags:
    - install_twitch_curses
    - twitch_curses


- name: Create streamlink config directory
  file:
    path: $HOME/.config/streamlink
    state: directory
  tags:
    - configure_streamlink
    - twitch_curses


- name: Update streamlink config
  copy:
    content: "player=mpv --cache 30480\n"
    dest: $HOME/.config/streamlink/config
  tags:
    - configure_streamlink
    - twitch_curses
