# Looks like the role is deprecated - we can now just download the aur collection
---
- name: Install base-devel pkg group
  community.general.pacman:
    name: base-devel
  become: true
  tags:
    - ansible_aur

- name: Clone git repo
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/ansible-aur-git.git'
    dest: /tmp/ansible_aur_git
    version: master
    depth: 1
  become: true
  become_user: "{{ aur_user }}"
  tags:
    - ansible_aur

- name: Build and install package
  ansible.builtin.command: makepkg --noconfirm --clean --install --cleanbuild --syncdeps
  args:
    chdir: /tmp/ansible_aur_git
  changed_when: false
  become: true
  become_user: "{{ aur_user }}"
  tags:
    - ansible_aur

- name: remove temp dir
  ansible.builtin.file:
    path: /tmp/ansible_aur_git
    state: absent
  become: true
  tags:
    - ansible_aur
