---
- name: Install base-delev pkg group
  pacman:
    name: base-devel
  become: yes
  tags:
    - ansible_aur


- name: Create aur user
  include_role:
    name: create_aur_user
  tags:
    - ansible_aur
    - aur_builder


- name: clone git repo
  git:
    repo: 'https://aur.archlinux.org/ansible-aur-git.git'
    dest: /tmp/ansible_aur_git
  become: yes
  become_user: "{{ aur_user }}"
  tags:
    - ansible_aur


- name: make package
  command: makepkg --noconfirm --clean --install --cleanbuild --syncdeps
  args:
    chdir: /tmp/ansible_aur_git
  become: yes
  become_user: "{{ aur_user }}"
  tags:
    - ansible_aur


- name: remove temp dir
  file:
    path: /tmp/ansible_aur_git
    state: absent
  become: yes
  tags:
    - ansible_aur
