---
- name: Install base-devel pkg group
  pacman:
    name: base-devel
  become: true
  tags:
    - ansible_aur


- name: Create aur user
  ansible.builtin.include_role:
    name: create_aur_user
  tags:
    - ansible_aur
    - aur_builder


- name: clone git repo
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/ansible-aur-git.git'
    dest: /tmp/ansible_aur_git
  become: true
  become_user: "{{ aur_user }}"
  tags:
    - ansible_aur


- name: make package
  ansible.builtin.command: makepkg --noconfirm --clean --install --cleanbuild --syncdeps
  args:
    chdir: /tmp/ansible_aur_git
  become: true
  become_user: "{{ aur_user }}"
  tags:
    - ansible_aur


- name: remove temp dir
  ansible.builtin.file:
    path: /tmp/ansible_aur_git
    state: absent
  become: true
  tags:
    - ansible_aur
