---
- name: Install required packages
  community.general.pacman:
    name: python-kubernetes

- name: "Create namespace {{ role_name }}"
  kubernetes.core.k8s:
    name: "{{ role_name }}"
    kind: Namespace
    state: present
  become: true
  become_user: minikube

- name: Create manifests directory
  file:
    path: "$HOME/manifests/{{ role_name }}"
    state: directory
    mode: "0700"
  become: true
  become_user: minikube

- name: Download manifest
  get_url:
    dest: "$HOME/manifests/{{ role_name }}/install.yaml"
    url: "https://raw.githubusercontent.com/argoproj/argo-cd/v{{ argocd_version }}/manifests/install.yaml"
    mode: "0600"
  become: true
  become_user: minikube

- name: Deploy {{ role_name }}
  kubernetes.core.k8s:
    state: present
    namespace: "{{ role_name }}"
    src: "$HOME/manifests/{{ role_name }}/install.yaml"
  become: true
  become_user: minikube

- name: Get admin password
  shell: 'kubectl -n {{ role_name }} get secret {{ role_name }}-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d'
  changed_when: false
  register: argocd_admin_password
  become: true
  become_user: minikube

- name: Show admin password
  debug:
    var: argocd_admin_password.stdout
