---
- name: Create minikube user
  user:
    name: "{{ minikube_user }}"
    system: true
    groups: docker

- name: Install minikube
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution | lower }}.yml"
