---
- name: Create minikube user
  ansible.builtin.user:
    name: "{{ minikube_user }}"
    system: true
    shell: /usr/bin/bash
    groups: docker

- name: Add kubectl alias
  ansible.builtin.lineinfile:
    regexp: "^alias k="
    line: "alias k='minikube kubectl --'"
    path: "$HOME/.bashrc"
  become: true
  become_user: "{{ minikube_user }}"

- name: Install minikube
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution | lower }}.yml"
