---
- name: Add firefox PPA repository into sources list
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/ppa
    state: present
  become: true


- name: Set apt priority to install firefox from apt repo
  ansible.builtin.copy:
    src: mozilla-firefox
    dest: /etc/apt/preferences.d/mozilla-firefox
    mode: "0644"
  become: true


- name: Install packages
  ansible.builtin.apt:
    name: firefox
    state: latest
    allow_downgrade: true
    update_cache: true
  become: true
