---
- name: update_apt_package_cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: gdm_restart
  ansible.builtin.systemd_service:
    name: gdm
    state: restarted
  become: true

- name: reload_mako_config
  ansible.builtin.command:
    cmd: makoctl reload
  changed_when: false
  failed_when: false

- name: reload_waybar_config
  ansible.builtin.command:
    cmd: pkill -SIGUSR2 -x waybar
  changed_when: false
  failed_when: false
