---
- name: Create conf.d directory
  file:
    path: "{{ conf_d_path }}"
    state: directory
    owner: root
  become: yes
  tags:
    - systemd
    - journald


- name: Copy journald config
  copy:
    src: "{{ item }}"
    dest: "{{ conf_d_path }}"
  with_fileglob:
    - files/*
  become: yes
  tags:
    - systemd
    - journald


- name: Restart journald
  service:
    name: systemd-journald
    state: restarted
  become: yes
  ignore_errors: yes
  tags:
    - systemd
    - journald
