---
- name: Create conf.d directory
  ansible.builtin.file:
    path: "{{ systemd_journald_conf_d_path }}"
    state: directory
    mode: "0755"
  become: true

- name: Copy journald config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ systemd_journald_conf_d_path }}"
    mode: "0644"
  with_fileglob:
    - files/*
  become: true
  notify: restart_journald
