---
- name: Create conf.d directory
  ansible.builtin.file:
    path: "{{ systemd_journald_conf_d_path }}"
    state: directory
    mode: "0755"
  become: true
  tags:
    - systemd
    - journald


- name: Copy journald config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ systemd_journald_conf_d_path }}"
    mode: "0644"
  with_fileglob:
    - files/*
  become: true
  tags:
    - systemd
    - journald


- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  become: true
  tags:
    - systemd
    - journald
