---
- name: Limit systemd log size
  replace:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp1 }}"
    replace: "{{ item.replace }}"
  with_items: "{{ items }}"
  vars:
    items:
      - path: /etc/systemd/journald.conf
        regexp1: '^#SystemMaxUse=$'
        replace: 'SystemMaxUse=75M'
  ignore_errors: yes
  become: yes
  tags:
    - systemd
    - journald


- name: Restart journald
  service:
    name: systemd-journald
    state: restarted
#  when: systemd_logsize.changed
  become: yes
  ignore_errors: yes
  tags:
    - systemd
    - journald
