---
- name: start_minikube
  ansible.builtin.command: 'minikube start --container-runtime=containerd'
  changed_when: false
  become: true
  become_user: "{{ minikube_user }}"

- name: download_kubectl
  ansible.builtin.command: 'minikube kubectl -- get pods -A'
  become: true
  become_user: "{{ minikube_user }}"
  changed_when: false
