---
install_packages_arch:
  aur:
    - blueman
    - gnome-keyring
    - gnome-screenshot
    - gpicview
    - libreoffice-fresh
    - mpv
    - mpv-mpris
    - nextcloud-client
    - pinta
    - pycharm
    - remmina
    - slack-desktop
    - smplayer
    - transmission-qt
